# Generated by Django 4.2.1 on 2023-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=150)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
